version: '3.8'
services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dibyajyotimishra
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis



volumes:
  mongo-db: